### PR TITLE
Align edit to right side

### PR DESCRIPTION
**Pull request by karishmakarki1**
HI,
I have modified on indexing_form.dart file for aligning Edit.
Here, is the screenshot of userid with Admin role.
Align Edit   Icon Right side-Admin role

Here, is the screenshot of userid without Admin role.
Align Edit   Icon Right side-user role

### CODE REVIEW

**Review by wanlok — APPROVED** [review]
I think pubspec.lock file should not be included in the PR

**Review by wanlok — CHANGES_REQUESTED** [review]
remove commented codes

**Comment by karishmakarki1** [comment]
> I think pubspec.lock file should not be included in the PR

I have just revert the particular commit.

**Review by wanlok — APPROVED** [review]

**Comment by karishmakarki1** [comment]
> remove commented codes
Done have a look

**Pull request merged**
