### PR TITLE
Align edit functions to the right of the widgets

### PR DESCRIPTION
**Pull request by karishmakarki1**
Here, is the result:
Steps:
1) Had modified the code on List_Details file by adding Align().
2) Had modified the code on Indexing_form file by adding Align ().

Align Edit Right

### CODE REVIEW

**Comment by karishmakarki1** [comment]
Here, is the result:
Steps:
Had modified the code on List_Details file.
Had modified the code on Indexing_form file.

Align Edit   Icon Right side

**Review by chullman — CHANGES_REQUESTED** [review]
Looks good, but I think leave the broken timestamp code in search_details.dart commented out, rather than remove it entirely, so that we can revisit the issue later. Like so: 

image

**Review by chullman — DISMISSED** [review]

**Review by chullman — CHANGES_REQUESTED** [review]
Line 41 with `SearchResults` function can't be removed, it must stay for the search results to display.

image

This also means at the top of `search_details.dart` this library must be imported:

```dart
import 'package:screensite/search/search_results.dart';
```

**Comment by karishmakarki1** [comment]
I have updated on my Branch and push it.

**Review by chullman — APPROVED** [review]

**Review by kovarny — APPROVED** [review]

**Review by kovarny — APPROVED** [review]

**Review by kovarny — APPROVED** [review]

**Pull request merged**
